/// Flutter icons Chef_hat
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Chef_hat
///      fonts:
///       - asset: fonts/Chef_hat.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Chef_hat {
  Chef_hat._();

  static const _kFontFam = 'Chef_hat';
  static const _kFontPkg = null;

  static const IconData chef_hat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
